// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: RadioClock

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_mainScreen_screen_init();
    ui_calendarScreen_screen_init();
    ui_timeSettings_screen_init();
    ui_MenuScreen_screen_init();
    ui_settingsScreen_screen_init();
    ui_alarmScreen_screen_init();
    ui_RadioScreen_screen_init();
    ui_MusicScreen_screen_init();
    ui_WifiScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_mainScreen);
}

void ui_destroy(void)
{
    ui_mainScreen_screen_destroy();
    ui_calendarScreen_screen_destroy();
    ui_timeSettings_screen_destroy();
    ui_MenuScreen_screen_destroy();
    ui_settingsScreen_screen_destroy();
    ui_alarmScreen_screen_destroy();
    ui_RadioScreen_screen_destroy();
    ui_MusicScreen_screen_destroy();
    ui_WifiScreen_screen_destroy();
}
