// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: RadioClock

#ifndef _RADIOCLOCK_UI_H
#define _RADIOCLOCK_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_mainScreen.h"
#include "ui_calendarScreen.h"
#include "ui_timeSettings.h"
#include "ui_MenuScreen.h"
#include "ui_settingsScreen.h"
#include "ui_alarmScreen.h"
#include "ui_RadioScreen.h"
#include "ui_MusicScreen.h"
#include "ui_WifiScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bgone_png);    // assets/bgOne.png
LV_IMG_DECLARE(ui_img_im_4_png);    // assets/im_4.png
LV_IMG_DECLARE(ui_img_angleright_png);    // assets/angleright.png
LV_IMG_DECLARE(ui_img_alarm_png);    // assets/alarm.png
LV_IMG_DECLARE(ui_img_battery_0_png);    // assets/battery_0.png
LV_IMG_DECLARE(ui_img_angleleft_png);    // assets/angleLeft.png
LV_IMG_DECLARE(ui_img_set_png);    // assets/SET.png
LV_IMG_DECLARE(ui_img_ok_png);    // assets/OK.png
LV_IMG_DECLARE(ui_img_radio_png);    // assets/radio.png
LV_IMG_DECLARE(ui_img_calendar_png);    // assets/calendar.png
LV_IMG_DECLARE(ui_img_499794662);    // assets/time-management.png
LV_IMG_DECLARE(ui_img_1725651404);    // assets/quality-control.png
LV_IMG_DECLARE(ui_img_clock_png);    // assets/clock.png
LV_IMG_DECLARE(ui_img_wifi_icon_png);    // assets/Wifi_icon.png
LV_IMG_DECLARE(ui_img_music_png);    // assets/Music.png
LV_IMG_DECLARE(ui_img_inc_png);    // assets/inc.png
LV_IMG_DECLARE(ui_img_dec_png);    // assets/dec.png
LV_IMG_DECLARE(ui_img_sound_png);    // assets/sound.png
LV_IMG_DECLARE(ui_img_mute_png);    // assets/mute.png

// FONTS
LV_FONT_DECLARE(ui_font_Font2);
LV_FONT_DECLARE(ui_font_FontTwo);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
