// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: RadioClock

#ifndef UI_ALARMSCREEN_H
#define UI_ALARMSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_alarmScreen
extern void ui_alarmScreen_screen_init(void);
extern void ui_alarmScreen_screen_destroy(void);
extern lv_obj_t * ui_alarmScreen;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_ampm2;
extern lv_obj_t * ui_alarmTimeContainer;
extern lv_obj_t * ui_HourContainer2;
extern lv_obj_t * ui_alarmHour;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_MinuteContainer2;
extern lv_obj_t * ui_alarmMinute;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_SecondContainer2;
extern lv_obj_t * ui_alarmSecond;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_alarmSet;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_alarmReset;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_alarmContainer;
// CUSTOM VARIABLES
extern lv_obj_t * uic_alarmScreen;
extern lv_obj_t * uic_alarmHour;
extern lv_obj_t * uic_alarmMinute;
extern lv_obj_t * uic_alarmSecond;
extern lv_obj_t * uic_alarmSet;
extern lv_obj_t * uic_Label10;
extern lv_obj_t * uic_alarmContainer;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

