// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: RadioClock

#include "ui.h"

lv_obj_t * uic_alarmContainer;
lv_obj_t * uic_Label10;
lv_obj_t * uic_alarmSet;
lv_obj_t * uic_alarmSecond;
lv_obj_t * uic_alarmMinute;
lv_obj_t * uic_alarmHour;
lv_obj_t * uic_alarmScreen;
lv_obj_t * ui_alarmScreen = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_ampm2 = NULL;
lv_obj_t * ui_alarmTimeContainer = NULL;
lv_obj_t * ui_HourContainer2 = NULL;
lv_obj_t * ui_alarmHour = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_MinuteContainer2 = NULL;
lv_obj_t * ui_alarmMinute = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_SecondContainer2 = NULL;
lv_obj_t * ui_alarmSecond = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_alarmSet = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_alarmReset = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_alarmContainer = NULL;
// event funtions
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 1500, 0, &ui_MenuScreen_screen_init);
    }
}

// build funtions

void ui_alarmScreen_screen_init(void)
{
    ui_alarmScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_alarmScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_alarmScreen, lv_color_hex(0x1A1A2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_alarmScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_button_create(ui_alarmScreen);
    lv_obj_set_width(ui_Button4, 81);
    lv_obj_set_height(ui_Button4, 65);
    lv_obj_set_x(ui_Button4, -115);
    lv_obj_set_y(ui_Button4, 82);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Button4, &ui_img_angleleft_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Button4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Button4, &ui_img_angleleft_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_image_recolor(ui_Button4, lv_color_hex(0xFFF800), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_image_recolor_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Image1 = lv_image_create(ui_alarmScreen);
    lv_image_set_src(ui_Image1, &ui_img_clock_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image1, -116);
    lv_obj_set_y(ui_Image1, -77);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ampm2 = lv_dropdown_create(ui_alarmScreen);
    lv_dropdown_set_options(ui_ampm2, "AM\nPM");
    lv_obj_set_width(ui_ampm2, 80);
    lv_obj_set_height(ui_ampm2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ampm2, 126);
    lv_obj_set_y(ui_ampm2, 131);
    lv_obj_add_flag(ui_ampm2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_ampm2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ampm2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ampm2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ampm2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ampm2, lv_color_hex(0xF2CC8F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ampm2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ampm2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_ampm2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ampm2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_ampm2), lv_color_hex(0xFFFFFF),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_ampm2), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_ampm2), lv_color_hex(0x626562),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_ampm2), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(lv_dropdown_get_list(ui_ampm2), lv_color_hex(0x393838),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_ampm2), lv_color_hex(0x0B7AFF),  LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_ampm2), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(lv_dropdown_get_list(ui_ampm2), lv_color_hex(0x000000),
                                  LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_dropdown_get_list(ui_ampm2), 0,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_alarmTimeContainer = lv_obj_create(ui_alarmScreen);
    lv_obj_remove_style_all(ui_alarmTimeContainer);
    lv_obj_set_width(ui_alarmTimeContainer, 188);
    lv_obj_set_height(ui_alarmTimeContainer, 119);
    lv_obj_set_x(ui_alarmTimeContainer, 126);
    lv_obj_set_y(ui_alarmTimeContainer, 2);
    lv_obj_set_flex_flow(ui_alarmTimeContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_alarmTimeContainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_alarmTimeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_alarmTimeContainer, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_alarmTimeContainer, lv_color_hex(0x10E408), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_alarmTimeContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_alarmTimeContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HourContainer2 = lv_obj_create(ui_alarmTimeContainer);
    lv_obj_remove_style_all(ui_HourContainer2);
    lv_obj_set_width(ui_HourContainer2, 58);
    lv_obj_set_height(ui_HourContainer2, 110);
    lv_obj_set_x(ui_HourContainer2, -101);
    lv_obj_set_y(ui_HourContainer2, -41);
    lv_obj_set_align(ui_HourContainer2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_HourContainer2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_HourContainer2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_HourContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_alarmHour = lv_roller_create(ui_HourContainer2);
    lv_roller_set_options(ui_alarmHour, "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12", LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_alarmHour, 5, LV_ANIM_OFF);
    lv_obj_set_width(ui_alarmHour, 50);
    lv_obj_set_height(ui_alarmHour, 90);
    lv_obj_set_x(ui_alarmHour, 25);
    lv_obj_set_y(ui_alarmHour, 86);
    lv_obj_set_style_bg_color(ui_alarmHour, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_alarmHour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_alarmHour, lv_color_hex(0xD1D1D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_alarmHour, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_alarmHour, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_alarmHour, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_alarmHour, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_alarmHour, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_alarmHour, &lv_font_montserrat_24, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_alarmHour, lv_color_hex(0x5FBFF1), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_alarmHour, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_alarmHour, lv_color_hex(0x1635E3), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_alarmHour, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_alarmHour, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_alarmHour, LV_GRAD_DIR_HOR, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_HourContainer2);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 42);
    lv_obj_set_y(ui_Label11, 123);
    lv_label_set_text(ui_Label11, "Hour");
    lv_obj_remove_flag(ui_Label11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MinuteContainer2 = lv_obj_create(ui_alarmTimeContainer);
    lv_obj_remove_style_all(ui_MinuteContainer2);
    lv_obj_set_width(ui_MinuteContainer2, 59);
    lv_obj_set_height(ui_MinuteContainer2, 120);
    lv_obj_set_x(ui_MinuteContainer2, 102);
    lv_obj_set_y(ui_MinuteContainer2, 18);
    lv_obj_set_flex_flow(ui_MinuteContainer2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_MinuteContainer2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MinuteContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_alarmMinute = lv_roller_create(ui_MinuteContainer2);
    lv_roller_set_options(ui_alarmMinute,
                          "1\n2\n3\n4\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n",
                          LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_alarmMinute, 20, LV_ANIM_OFF);
    lv_obj_set_width(ui_alarmMinute, 50);
    lv_obj_set_height(ui_alarmMinute, 90);
    lv_obj_set_x(ui_alarmMinute, 201);
    lv_obj_set_y(ui_alarmMinute, 20);
    lv_obj_set_style_shadow_color(ui_alarmMinute, lv_color_hex(0xD1D1D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_alarmMinute, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_alarmMinute, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_alarmMinute, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_alarmMinute, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_alarmMinute, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_alarmMinute, &lv_font_montserrat_24, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_alarmMinute, lv_color_hex(0x5FBFF1), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_alarmMinute, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_alarmMinute, lv_color_hex(0x1635E3), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_alarmMinute, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_alarmMinute, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_alarmMinute, LV_GRAD_DIR_HOR, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_MinuteContainer2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 114);
    lv_obj_set_y(ui_Label4, 122);
    lv_label_set_text(ui_Label4, "Minute");
    lv_obj_remove_flag(ui_Label4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SecondContainer2 = lv_obj_create(ui_alarmTimeContainer);
    lv_obj_remove_style_all(ui_SecondContainer2);
    lv_obj_set_width(ui_SecondContainer2, 63);
    lv_obj_set_height(ui_SecondContainer2, 116);
    lv_obj_set_x(ui_SecondContainer2, 171);
    lv_obj_set_y(ui_SecondContainer2, 25);
    lv_obj_set_flex_flow(ui_SecondContainer2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SecondContainer2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SecondContainer2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_alarmSecond = lv_roller_create(ui_SecondContainer2);
    lv_roller_set_options(ui_alarmSecond,
                          "1\n2\n3\n4\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n",
                          LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_alarmSecond, 30, LV_ANIM_OFF);
    lv_obj_set_width(ui_alarmSecond, 50);
    lv_obj_set_height(ui_alarmSecond, 90);
    lv_obj_set_x(ui_alarmSecond, 200);
    lv_obj_set_y(ui_alarmSecond, 24);
    lv_obj_set_style_shadow_color(ui_alarmSecond, lv_color_hex(0xD1D1D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_alarmSecond, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_alarmSecond, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_alarmSecond, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_alarmSecond, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_alarmSecond, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_alarmSecond, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_alarmSecond, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_alarmSecond, &lv_font_montserrat_24, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_alarmSecond, lv_color_hex(0x5FBFF1), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_alarmSecond, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_alarmSecond, lv_color_hex(0x1635E3), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_alarmSecond, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_alarmSecond, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_alarmSecond, LV_GRAD_DIR_HOR, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_SecondContainer2);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 181);
    lv_obj_set_y(ui_Label9, 122);
    lv_label_set_text(ui_Label9, "Seconds");
    lv_obj_remove_flag(ui_Label9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_alarmSet = lv_button_create(ui_alarmScreen);
    lv_obj_set_width(ui_alarmSet, 80);
    lv_obj_set_height(ui_alarmSet, 35);
    lv_obj_set_x(ui_alarmSet, 215);
    lv_obj_set_y(ui_alarmSet, 132);
    lv_obj_add_flag(ui_alarmSet, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_alarmSet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_alarmSet, lv_color_hex(0xE07A5F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_alarmSet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_alarmSet, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_alarmSet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_alarmSet, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_alarmSet);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "SET");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_alarmReset = lv_button_create(ui_alarmScreen);
    lv_obj_set_width(ui_alarmReset, 133);
    lv_obj_set_height(ui_alarmReset, 35);
    lv_obj_set_x(ui_alarmReset, 149);
    lv_obj_set_y(ui_alarmReset, 176);
    lv_obj_add_flag(ui_alarmReset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_alarmReset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_alarmReset, lv_color_hex(0x81B29A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_alarmReset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_alarmReset, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_alarmReset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_alarmReset, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_alarmReset);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "RESET");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_alarmContainer = lv_obj_create(ui_alarmScreen);
    lv_obj_remove_style_all(ui_alarmContainer);
    lv_obj_set_width(ui_alarmContainer, 100);
    lv_obj_set_height(ui_alarmContainer, 75);
    lv_obj_set_x(ui_alarmContainer, 10);
    lv_obj_set_y(ui_alarmContainer, 93);
    lv_obj_set_flex_flow(ui_alarmContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_alarmContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_alarmContainer, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_alarmContainer, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_alarmContainer, lv_color_hex(0x3D405B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_alarmContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    uic_alarmScreen = ui_alarmScreen;
    uic_alarmHour = ui_alarmHour;
    uic_alarmMinute = ui_alarmMinute;
    uic_alarmSecond = ui_alarmSecond;
    uic_alarmSet = ui_alarmSet;
    uic_Label10 = ui_Label10;
    uic_alarmContainer = ui_alarmContainer;

}

void ui_alarmScreen_screen_destroy(void)
{
    if(ui_alarmScreen) lv_obj_del(ui_alarmScreen);

    // NULL screen variables
    uic_alarmScreen = NULL;
    ui_alarmScreen = NULL;
    ui_Button4 = NULL;
    ui_Image1 = NULL;
    ui_ampm2 = NULL;
    ui_alarmTimeContainer = NULL;
    ui_HourContainer2 = NULL;
    uic_alarmHour = NULL;
    ui_alarmHour = NULL;
    ui_Label11 = NULL;
    ui_MinuteContainer2 = NULL;
    uic_alarmMinute = NULL;
    ui_alarmMinute = NULL;
    ui_Label4 = NULL;
    ui_SecondContainer2 = NULL;
    uic_alarmSecond = NULL;
    ui_alarmSecond = NULL;
    ui_Label9 = NULL;
    uic_alarmSet = NULL;
    ui_alarmSet = NULL;
    ui_Label12 = NULL;
    ui_alarmReset = NULL;
    uic_Label10 = NULL;
    ui_Label10 = NULL;
    uic_alarmContainer = NULL;
    ui_alarmContainer = NULL;

}
