// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: RadioClock

#ifndef UI_CALENDARSCREEN_H
#define UI_CALENDARSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_calendarScreen
extern void ui_calendarScreen_screen_init(void);
extern void ui_calendarScreen_screen_destroy(void);
extern void ui_event_calendarScreen(lv_event_t * e);
extern lv_obj_t * ui_calendarScreen;
extern lv_obj_t * ui_calendar;
extern void ui_event_backFromCalendarToMenuScreen(lv_event_t * e);
extern lv_obj_t * ui_backFromCalendarToMenuScreen;
// CUSTOM VARIABLES
extern lv_obj_t * uic_calendarScreen;
extern lv_obj_t * uic_calendar;
extern lv_obj_t * uic_backFromCalendarToMenuScreen;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

