// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: RadioClock

#include "ui.h"

lv_obj_t * uic_backFromCalendarToMenuScreen;
lv_obj_t * uic_calendar;
lv_obj_t * uic_calendarScreen;
lv_obj_t * ui_calendarScreen = NULL;
lv_obj_t * ui_calendar = NULL;
lv_obj_t * ui_backFromCalendarToMenuScreen = NULL;
// event funtions
void ui_event_calendarScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_MenuScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MenuScreen_screen_init);
    }
}

void ui_event_backFromCalendarToMenuScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 1500, 0, &ui_MenuScreen_screen_init);
    }
}

// build funtions

void ui_calendarScreen_screen_init(void)
{
    ui_calendarScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_calendarScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_calendarScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_calendarScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_calendar = lv_calendar_create(ui_calendarScreen);
    lv_obj_t * ui_calendar_header = lv_calendar_add_header_arrow(ui_calendar);
    lv_obj_set_width(ui_calendar, 297);
    lv_obj_set_height(ui_calendar, 186);
    lv_obj_set_x(ui_calendar, 14);
    lv_obj_set_y(ui_calendar, 1);

    ui_backFromCalendarToMenuScreen = lv_button_create(ui_calendarScreen);
    lv_obj_set_width(ui_backFromCalendarToMenuScreen, 51);
    lv_obj_set_height(ui_backFromCalendarToMenuScreen, 32);
    lv_obj_set_x(ui_backFromCalendarToMenuScreen, 259);
    lv_obj_set_y(ui_backFromCalendarToMenuScreen, 199);
    lv_obj_add_flag(ui_backFromCalendarToMenuScreen, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_backFromCalendarToMenuScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_backFromCalendarToMenuScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_backFromCalendarToMenuScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backFromCalendarToMenuScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_backFromCalendarToMenuScreen, &ui_img_angleleft_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_backFromCalendarToMenuScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_backFromCalendarToMenuScreen, lv_color_hex(0xFFFFFF),
                                      LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_backFromCalendarToMenuScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_backFromCalendarToMenuScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_backFromCalendarToMenuScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_backFromCalendarToMenuScreen, lv_color_hex(0x000000),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_backFromCalendarToMenuScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_backFromCalendarToMenuScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_backFromCalendarToMenuScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_backFromCalendarToMenuScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_backFromCalendarToMenuScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_backFromCalendarToMenuScreen, &ui_img_angleleft_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_image_recolor(ui_backFromCalendarToMenuScreen, lv_color_hex(0xFFF400),
                                      LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_image_recolor_opa(ui_backFromCalendarToMenuScreen, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_backFromCalendarToMenuScreen, ui_event_backFromCalendarToMenuScreen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_calendarScreen, ui_event_calendarScreen, LV_EVENT_ALL, NULL);
    uic_calendarScreen = ui_calendarScreen;
    uic_calendar = ui_calendar;
    uic_backFromCalendarToMenuScreen = ui_backFromCalendarToMenuScreen;

}

void ui_calendarScreen_screen_destroy(void)
{
    if(ui_calendarScreen) lv_obj_del(ui_calendarScreen);

    // NULL screen variables
    uic_calendarScreen = NULL;
    ui_calendarScreen = NULL;
    uic_calendar = NULL;
    ui_calendar = NULL;
    uic_backFromCalendarToMenuScreen = NULL;
    ui_backFromCalendarToMenuScreen = NULL;

}
