// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: RadioClock

#include "ui.h"

// COMPONENT circularArc

lv_obj_t * ui_circularArc_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_circularArc;
    cui_circularArc = lv_arc_create(comp_parent);
    lv_obj_set_width(cui_circularArc, 230);
    lv_obj_set_height(cui_circularArc, 230);
    lv_obj_set_x(cui_circularArc, -1);
    lv_obj_set_y(cui_circularArc, 0);
    lv_obj_set_align(cui_circularArc, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_circularArc, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_circularArc, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_arc_set_value(cui_circularArc, 12);
    lv_arc_set_bg_angles(cui_circularArc, 0, 360);
    lv_obj_set_style_arc_width(cui_circularArc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(cui_circularArc, lv_color_hex(0x35353A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(cui_circularArc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(cui_circularArc, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(cui_circularArc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(cui_circularArc, lv_color_hex(0x33FAFB), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_circularArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_circularArc, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_circularArc, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_circularArc, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_circularArc, 1, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_CIRCULARARC_NUM);
    children[UI_COMP_CIRCULARARC_CIRCULARARC] = cui_circularArc;
    lv_obj_add_event_cb(cui_circularArc, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_circularArc, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_circularArc_create_hook(cui_circularArc);
    return cui_circularArc;
}

