// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: RadioClock

#ifndef _UI_COMP_CIRCULARARC_H
#define _UI_COMP_CIRCULARARC_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT circularArc
#define UI_COMP_CIRCULARARC_CIRCULARARC 0
#define _UI_COMP_CIRCULARARC_NUM 1
lv_obj_t * ui_circularArc_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
