// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: RadioClock

#include "ui.h"

lv_obj_t * uic_backFromMenuToMainScreen;
lv_obj_t * uic_MusicBtn;
lv_obj_t * uic_WifiBtn;
lv_obj_t * uic_alarmScreenBtn;
lv_obj_t * uic_systemBtn;
lv_obj_t * uic_dateTimeChange;
lv_obj_t * uic_calendarBtn;
lv_obj_t * uic_radioBtn;
lv_obj_t * uic_MenuScreen;
lv_obj_t * ui_MenuScreen = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_radioBtn = NULL;
lv_obj_t * ui_calendarBtn = NULL;
lv_obj_t * ui_dateTimeChange = NULL;
lv_obj_t * ui_systemBtn = NULL;
lv_obj_t * ui_alarmScreenBtn = NULL;
lv_obj_t * ui_WifiBtn = NULL;
lv_obj_t * ui_MusicBtn = NULL;
lv_obj_t * ui_backFromMenuToMainScreen = NULL;
// event funtions
void ui_event_radioBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_RadioScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_RadioScreen_screen_init);
    }
}

void ui_event_calendarBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_calendarScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_calendarScreen_screen_init);
    }
}

void ui_event_dateTimeChange(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_timeSettings, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_timeSettings_screen_init);
    }
}

void ui_event_systemBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_settingsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_settingsScreen_screen_init);
    }
}

void ui_event_alarmScreenBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_alarmScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_alarmScreen_screen_init);
    }
}

void ui_event_WifiBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_WifiScreen_screen_init);
    }
}

void ui_event_MusicBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MusicScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MusicScreen_screen_init);
    }
}

void ui_event_backFromMenuToMainScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_mainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 1500, 0, &ui_mainScreen_screen_init);
    }
}

// build funtions

void ui_MenuScreen_screen_init(void)
{
    ui_MenuScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MenuScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MenuScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_MenuScreen);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 263);
    lv_obj_set_height(ui_Container1, 227);
    lv_obj_set_x(ui_Container1, 28);
    lv_obj_set_y(ui_Container1, 3);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container1, lv_color_hex(0x002A3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Container1, lv_color_hex(0x009CA7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Container1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Container1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Container1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_radioBtn = lv_button_create(ui_Container1);
    lv_obj_set_width(ui_radioBtn, 68);
    lv_obj_set_height(ui_radioBtn, 68);
    lv_obj_set_x(ui_radioBtn, 171);
    lv_obj_set_y(ui_radioBtn, 12);
    lv_obj_add_flag(ui_radioBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_radioBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_radioBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_radioBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_radioBtn, &ui_img_radio_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_radioBtn, lv_color_hex(0x1C8AFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_radioBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_radioBtn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_radioBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_radioBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_radioBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_calendarBtn = lv_button_create(ui_Container1);
    lv_obj_set_width(ui_calendarBtn, 68);
    lv_obj_set_height(ui_calendarBtn, 68);
    lv_obj_set_x(ui_calendarBtn, 19);
    lv_obj_set_y(ui_calendarBtn, 17);
    lv_obj_set_flex_flow(ui_calendarBtn, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_calendarBtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_calendarBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_calendarBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_calendarBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_calendarBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_calendarBtn, &ui_img_calendar_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_calendarBtn, lv_color_hex(0x1C8AFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_calendarBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_calendarBtn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_calendarBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_calendarBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dateTimeChange = lv_button_create(ui_Container1);
    lv_obj_set_width(ui_dateTimeChange, 68);
    lv_obj_set_height(ui_dateTimeChange, 68);
    lv_obj_set_x(ui_dateTimeChange, 94);
    lv_obj_set_y(ui_dateTimeChange, 17);
    lv_obj_add_flag(ui_dateTimeChange, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_dateTimeChange, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dateTimeChange, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dateTimeChange, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_dateTimeChange, &ui_img_499794662, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dateTimeChange, lv_color_hex(0x1C8AFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dateTimeChange, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dateTimeChange, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_dateTimeChange, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_dateTimeChange, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_dateTimeChange, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_systemBtn = lv_button_create(ui_Container1);
    lv_obj_set_width(ui_systemBtn, 68);
    lv_obj_set_height(ui_systemBtn, 68);
    lv_obj_set_x(ui_systemBtn, 17);
    lv_obj_set_y(ui_systemBtn, 86);
    lv_obj_add_flag(ui_systemBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_systemBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_systemBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_systemBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_systemBtn, &ui_img_1725651404, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_systemBtn, lv_color_hex(0x1C8AFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_systemBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_systemBtn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_systemBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_systemBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_alarmScreenBtn = lv_button_create(ui_Container1);
    lv_obj_set_width(ui_alarmScreenBtn, 68);
    lv_obj_set_height(ui_alarmScreenBtn, 68);
    lv_obj_set_x(ui_alarmScreenBtn, 17);
    lv_obj_set_y(ui_alarmScreenBtn, 86);
    lv_obj_add_flag(ui_alarmScreenBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_alarmScreenBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_alarmScreenBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_alarmScreenBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_alarmScreenBtn, &ui_img_clock_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_alarmScreenBtn, lv_color_hex(0x1267BF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_alarmScreenBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_alarmScreenBtn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_alarmScreenBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_alarmScreenBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiBtn = lv_button_create(ui_Container1);
    lv_obj_set_width(ui_WifiBtn, 68);
    lv_obj_set_height(ui_WifiBtn, 68);
    lv_obj_set_x(ui_WifiBtn, -52);
    lv_obj_set_y(ui_WifiBtn, 85);
    lv_obj_add_flag(ui_WifiBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_WifiBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_WifiBtn, &ui_img_wifi_icon_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_WifiBtn, lv_color_hex(0xFFF740), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_WifiBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WifiBtn, lv_color_hex(0x1267BF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WifiBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WifiBtn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_WifiBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_WifiBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MusicBtn = lv_button_create(ui_Container1);
    lv_obj_set_width(ui_MusicBtn, 68);
    lv_obj_set_height(ui_MusicBtn, 68);
    lv_obj_set_x(ui_MusicBtn, -52);
    lv_obj_set_y(ui_MusicBtn, 85);
    lv_obj_add_flag(ui_MusicBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MusicBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MusicBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MusicBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_MusicBtn, &ui_img_music_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_MusicBtn, lv_color_hex(0xEB5FFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_MusicBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MusicBtn, lv_color_hex(0x1267BF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MusicBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MusicBtn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_MusicBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_MusicBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backFromMenuToMainScreen = lv_button_create(ui_Container1);
    lv_obj_set_width(ui_backFromMenuToMainScreen, 81);
    lv_obj_set_height(ui_backFromMenuToMainScreen, 65);
    lv_obj_set_x(ui_backFromMenuToMainScreen, 188);
    lv_obj_set_y(ui_backFromMenuToMainScreen, 114);
    lv_obj_set_align(ui_backFromMenuToMainScreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backFromMenuToMainScreen, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_backFromMenuToMainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_backFromMenuToMainScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_backFromMenuToMainScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backFromMenuToMainScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_backFromMenuToMainScreen, &ui_img_angleleft_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_backFromMenuToMainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_backFromMenuToMainScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_backFromMenuToMainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_backFromMenuToMainScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_backFromMenuToMainScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_backFromMenuToMainScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_backFromMenuToMainScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_backFromMenuToMainScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_backFromMenuToMainScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_backFromMenuToMainScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_backFromMenuToMainScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_backFromMenuToMainScreen, &ui_img_angleleft_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_image_recolor(ui_backFromMenuToMainScreen, lv_color_hex(0xFFF400), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_image_recolor_opa(ui_backFromMenuToMainScreen, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_radioBtn, ui_event_radioBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_calendarBtn, ui_event_calendarBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dateTimeChange, ui_event_dateTimeChange, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_systemBtn, ui_event_systemBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_alarmScreenBtn, ui_event_alarmScreenBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WifiBtn, ui_event_WifiBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MusicBtn, ui_event_MusicBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_backFromMenuToMainScreen, ui_event_backFromMenuToMainScreen, LV_EVENT_ALL, NULL);
    uic_MenuScreen = ui_MenuScreen;
    uic_radioBtn = ui_radioBtn;
    uic_calendarBtn = ui_calendarBtn;
    uic_dateTimeChange = ui_dateTimeChange;
    uic_systemBtn = ui_systemBtn;
    uic_alarmScreenBtn = ui_alarmScreenBtn;
    uic_WifiBtn = ui_WifiBtn;
    uic_MusicBtn = ui_MusicBtn;
    uic_backFromMenuToMainScreen = ui_backFromMenuToMainScreen;

}

void ui_MenuScreen_screen_destroy(void)
{
    if(ui_MenuScreen) lv_obj_del(ui_MenuScreen);

    // NULL screen variables
    uic_MenuScreen = NULL;
    ui_MenuScreen = NULL;
    ui_Container1 = NULL;
    uic_radioBtn = NULL;
    ui_radioBtn = NULL;
    uic_calendarBtn = NULL;
    ui_calendarBtn = NULL;
    uic_dateTimeChange = NULL;
    ui_dateTimeChange = NULL;
    uic_systemBtn = NULL;
    ui_systemBtn = NULL;
    uic_alarmScreenBtn = NULL;
    ui_alarmScreenBtn = NULL;
    uic_WifiBtn = NULL;
    ui_WifiBtn = NULL;
    uic_MusicBtn = NULL;
    ui_MusicBtn = NULL;
    uic_backFromMenuToMainScreen = NULL;
    ui_backFromMenuToMainScreen = NULL;

}
