// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: RadioClock

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_mainScreen
extern void ui_mainScreen_screen_init(void);
extern void ui_mainScreen_screen_destroy(void);
extern lv_obj_t * ui_mainScreen;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Hours;
extern lv_obj_t * ui_colonone;
extern lv_obj_t * ui_Minutes;
extern lv_obj_t * ui_colonone2;
extern lv_obj_t * ui_Seconds;
extern lv_obj_t * ui_amPmLabel;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_day;
extern lv_obj_t * ui_monthDateYear;
extern lv_obj_t * ui_mainSpinner;
extern lv_obj_t * ui_tempArc;
extern lv_obj_t * ui_tempLabel;
extern lv_obj_t * ui_WeatherContainer;
extern lv_obj_t * ui_monthDateYear1;
extern lv_obj_t * ui_Image2;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_StatusContainer;
extern lv_obj_t * ui_StatusContainer1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_mainScreen;
extern lv_obj_t * uic_Seconds;
extern lv_obj_t * uic_amPmLabel;
extern lv_obj_t * uic_mainSpinner;
extern lv_obj_t * uic_tempArc;
extern lv_obj_t * uic_tempLabel;
extern lv_obj_t * uic_WeatherContainer;
extern lv_obj_t * uic_Image2;
extern lv_obj_t * uic_StatusContainer;
extern lv_obj_t * uic_batteryContainer;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

