// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: RadioClock

#ifndef UI_MUSICSCREEN_H
#define UI_MUSICSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MusicScreen
extern void ui_MusicScreen_screen_init(void);
extern void ui_MusicScreen_screen_destroy(void);
extern lv_obj_t * ui_MusicScreen;
extern void ui_event_backFromMusicToMenu(lv_event_t * e);
extern lv_obj_t * ui_backFromMusicToMenu;
// CUSTOM VARIABLES
extern lv_obj_t * uic_MusicScreen;
extern lv_obj_t * uic_backFromMusicToMenu;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

