// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: RadioClock

#ifndef UI_MENUSCREEN_H
#define UI_MENUSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MenuScreen
extern void ui_MenuScreen_screen_init(void);
extern void ui_MenuScreen_screen_destroy(void);
extern lv_obj_t * ui_MenuScreen;
extern lv_obj_t * ui_Container1;
extern void ui_event_radioBtn(lv_event_t * e);
extern lv_obj_t * ui_radioBtn;
extern void ui_event_calendarBtn(lv_event_t * e);
extern lv_obj_t * ui_calendarBtn;
extern void ui_event_dateTimeChange(lv_event_t * e);
extern lv_obj_t * ui_dateTimeChange;
extern void ui_event_systemBtn(lv_event_t * e);
extern lv_obj_t * ui_systemBtn;
extern void ui_event_alarmScreenBtn(lv_event_t * e);
extern lv_obj_t * ui_alarmScreenBtn;
extern void ui_event_WifiBtn(lv_event_t * e);
extern lv_obj_t * ui_WifiBtn;
extern void ui_event_MusicBtn(lv_event_t * e);
extern lv_obj_t * ui_MusicBtn;
extern void ui_event_backFromMenuToMainScreen(lv_event_t * e);
extern lv_obj_t * ui_backFromMenuToMainScreen;
// CUSTOM VARIABLES
extern lv_obj_t * uic_MenuScreen;
extern lv_obj_t * uic_radioBtn;
extern lv_obj_t * uic_calendarBtn;
extern lv_obj_t * uic_dateTimeChange;
extern lv_obj_t * uic_systemBtn;
extern lv_obj_t * uic_alarmScreenBtn;
extern lv_obj_t * uic_WifiBtn;
extern lv_obj_t * uic_MusicBtn;
extern lv_obj_t * uic_backFromMenuToMainScreen;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

