// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: RadioClock

#include "ui.h"

lv_obj_t * uic_batteryContainer;
lv_obj_t * uic_StatusContainer;
lv_obj_t * uic_Image2;
lv_obj_t * uic_WeatherContainer;
lv_obj_t * uic_tempLabel;
lv_obj_t * uic_tempArc;
lv_obj_t * uic_mainSpinner;
lv_obj_t * uic_amPmLabel;
lv_obj_t * uic_Seconds;
lv_obj_t * uic_mainScreen;
lv_obj_t * ui_mainScreen = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Hours = NULL;
lv_obj_t * ui_colonone = NULL;
lv_obj_t * ui_Minutes = NULL;
lv_obj_t * ui_colonone2 = NULL;
lv_obj_t * ui_Seconds = NULL;
lv_obj_t * ui_amPmLabel = NULL;
lv_obj_t * ui_Bar1 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_day = NULL;
lv_obj_t * ui_monthDateYear = NULL;
lv_obj_t * ui_mainSpinner = NULL;
lv_obj_t * ui_tempArc = NULL;
lv_obj_t * ui_tempLabel = NULL;
lv_obj_t * ui_WeatherContainer = NULL;
lv_obj_t * ui_monthDateYear1 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_StatusContainer = NULL;
lv_obj_t * ui_StatusContainer1 = NULL;
// event funtions
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 1500, 0, &ui_MenuScreen_screen_init);
    }
}

// build funtions

void ui_mainScreen_screen_init(void)
{
    ui_mainScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_mainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_main_stop(ui_mainScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_mainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_mainScreen, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_mainScreen, &ui_img_bgone_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_mainScreen, 220, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_mainScreen);
    lv_obj_set_width(ui_Panel1, 312);
    lv_obj_set_height(ui_Panel1, 105);
    lv_obj_set_x(ui_Panel1, 3);
    lv_obj_set_y(ui_Panel1, 19);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Panel1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Hours = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Hours, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Hours, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Hours, -119);
    lv_obj_set_y(ui_Hours, -10);
    lv_obj_set_align(ui_Hours, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Hours, "01");
    lv_obj_set_style_text_color(ui_Hours, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Hours, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Hours, &ui_font_FontTwo, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Hours, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Hours, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Hours, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Hours, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Hours, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Hours, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Hours, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Hours, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_colonone = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_colonone, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_colonone, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_colonone, -74);
    lv_obj_set_y(ui_colonone, -23);
    lv_obj_set_align(ui_colonone, LV_ALIGN_CENTER);
    lv_label_set_text(ui_colonone, ":");
    lv_obj_set_style_text_color(ui_colonone, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_colonone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_colonone, &ui_font_FontTwo, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Minutes = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Minutes, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Minutes, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Minutes, -27);
    lv_obj_set_y(ui_Minutes, -11);
    lv_obj_set_align(ui_Minutes, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Minutes, "54");
    lv_obj_set_style_text_color(ui_Minutes, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Minutes, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Minutes, &ui_font_FontTwo, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_colonone2 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_colonone2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_colonone2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_colonone2, 22);
    lv_obj_set_y(ui_colonone2, -22);
    lv_obj_set_align(ui_colonone2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_colonone2, ":");
    lv_obj_set_style_text_color(ui_colonone2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_colonone2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_colonone2, &ui_font_FontTwo, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Seconds = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Seconds, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Seconds, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Seconds, 74);
    lv_obj_set_y(ui_Seconds, -11);
    lv_obj_set_align(ui_Seconds, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Seconds, "48");
    lv_obj_set_style_text_color(ui_Seconds, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Seconds, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Seconds, &ui_font_FontTwo, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_amPmLabel = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_amPmLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_amPmLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_amPmLabel, 272);
    lv_obj_set_y(ui_amPmLabel, 39);
    lv_label_set_text(ui_amPmLabel, "PM");
    lv_obj_set_style_text_color(ui_amPmLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_amPmLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_amPmLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_amPmLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_amPmLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar1 = lv_bar_create(ui_Panel1);
    lv_bar_set_value(ui_Bar1, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 307);
    lv_obj_set_height(ui_Bar1, 3);
    lv_obj_set_x(ui_Bar1, 4);
    lv_obj_set_y(ui_Bar1, 74);
    lv_obj_set_style_radius(ui_Bar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_Bar1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Bar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bar1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Bar1, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar1,
                                                                                           lv_obj_get_style_pad_right(ui_Bar1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Container2 = lv_obj_create(ui_mainScreen);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 152);
    lv_obj_set_height(ui_Container2, 75);
    lv_obj_set_x(ui_Container2, 5);
    lv_obj_set_y(ui_Container2, 162);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Container2, lv_color_hex(0xEBEBEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container2, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_day, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day, -14);
    lv_obj_set_y(ui_day, -2);
    lv_obj_set_align(ui_day, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day, "SAT");
    lv_obj_set_style_text_color(ui_day, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_monthDateYear = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_monthDateYear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_monthDateYear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_monthDateYear, 17);
    lv_obj_set_y(ui_monthDateYear, 71);
    lv_label_set_text(ui_monthDateYear, "Feb 14 , 2026");
    lv_obj_set_style_text_color(ui_monthDateYear, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_monthDateYear, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_monthDateYear, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainSpinner = lv_spinner_create(ui_mainScreen);
    //lv_spinner_set_anim_params(ui_mainSpinner, 1000, 90);
    lv_obj_set_width(ui_mainSpinner, 42);
    lv_obj_set_height(ui_mainSpinner, 37);
    lv_obj_set_x(ui_mainSpinner, 277);
    lv_obj_set_y(ui_mainSpinner, 4);
    lv_obj_remove_flag(ui_mainSpinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_mainSpinner, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_mainSpinner, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_mainSpinner, lv_color_hex(0xE3FF12), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_mainSpinner, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_mainSpinner, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_mainSpinner, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_tempArc = lv_arc_create(ui_mainScreen);
    lv_obj_set_width(ui_tempArc, 95);
    lv_obj_set_height(ui_tempArc, 88);
    lv_obj_set_x(ui_tempArc, 223);
    lv_obj_set_y(ui_tempArc, 100);
    lv_arc_set_value(ui_tempArc, 50);
    lv_obj_set_style_arc_color(ui_tempArc, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_tempArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_tempArc, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_tempArc, lv_color_hex(0xDAFF40), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_tempArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_tempArc, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_tempArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_tempArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_tempLabel = lv_label_create(ui_tempArc);
    lv_obj_set_width(ui_tempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempLabel, -2);
    lv_obj_set_y(ui_tempLabel, 0);
    lv_obj_set_align(ui_tempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempLabel, "33°");
    lv_obj_set_style_text_color(ui_tempLabel, lv_color_hex(0xFDFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherContainer = lv_obj_create(ui_mainScreen);
    lv_obj_remove_style_all(ui_WeatherContainer);
    lv_obj_set_width(ui_WeatherContainer, 152);
    lv_obj_set_height(ui_WeatherContainer, 61);
    lv_obj_set_x(ui_WeatherContainer, 5);
    lv_obj_set_y(ui_WeatherContainer, 98);
    lv_obj_remove_flag(ui_WeatherContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WeatherContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WeatherContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WeatherContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WeatherContainer, lv_color_hex(0xF5F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WeatherContainer, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WeatherContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_shadow_color(ui_WeatherContainer, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_WeatherContainer, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_WeatherContainer, 1, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_WeatherContainer, 1, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_WeatherContainer, 1, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_WeatherContainer, 1, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_monthDateYear1 = lv_label_create(ui_WeatherContainer);
    lv_obj_set_width(ui_monthDateYear1, 73);
    lv_obj_set_height(ui_monthDateYear1, 43);
    lv_obj_set_x(ui_monthDateYear1, -34);
    lv_obj_set_y(ui_monthDateYear1, 6);
    lv_obj_set_align(ui_monthDateYear1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_monthDateYear1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_monthDateYear1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_monthDateYear1, "ThunderStorm");
    lv_obj_set_style_text_color(ui_monthDateYear1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_monthDateYear1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_monthDateYear1, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_monthDateYear1, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_WeatherContainer);
    lv_image_set_src(ui_Image2, &ui_img_im_4_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image2, 44);
    lv_obj_set_y(ui_Image2, -2);
    lv_obj_set_align(ui_Image2, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Image2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Image2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_button_create(ui_mainScreen);
    lv_obj_set_width(ui_Button1, 81);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, 125);
    lv_obj_set_y(ui_Button1, 89);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Button1, &ui_img_angleright_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Button1, &ui_img_angleright_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_image_recolor(ui_Button1, lv_color_hex(0xFAFF00), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_image_recolor_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_StatusContainer = lv_obj_create(ui_mainScreen);
    lv_obj_remove_style_all(ui_StatusContainer);
    lv_obj_set_width(ui_StatusContainer, 20);
    lv_obj_set_height(ui_StatusContainer, 21);
    lv_obj_set_x(ui_StatusContainer, 38);
    lv_obj_set_y(ui_StatusContainer, 0);
    lv_obj_remove_flag(ui_StatusContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatusContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_StatusContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StatusContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_StatusContainer, &ui_img_alarm_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_StatusContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_StatusContainer, lv_color_hex(0xA4FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_StatusContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatusContainer, lv_color_hex(0xF5F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatusContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_shadow_color(ui_StatusContainer, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_StatusContainer, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_StatusContainer, 1, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_StatusContainer, 1, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_StatusContainer, 1, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_StatusContainer, 1, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_StatusContainer1 = lv_obj_create(ui_mainScreen);
    lv_obj_remove_style_all(ui_StatusContainer1);
    lv_obj_set_width(ui_StatusContainer1, 18);
    lv_obj_set_height(ui_StatusContainer1, 26);
    lv_obj_set_x(ui_StatusContainer1, 29);
    lv_obj_set_y(ui_StatusContainer1, 0);
    lv_obj_remove_flag(ui_StatusContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatusContainer1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_StatusContainer1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StatusContainer1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_StatusContainer1, &ui_img_battery_0_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_StatusContainer1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_StatusContainer1, lv_color_hex(0x9CFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_StatusContainer1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StatusContainer1, lv_color_hex(0xF5F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StatusContainer1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_StatusContainer1, 900, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_shadow_color(ui_StatusContainer1, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_StatusContainer1, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_StatusContainer1, 1, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_StatusContainer1, 1, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_StatusContainer1, 1, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_StatusContainer1, 1, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    uic_mainScreen = ui_mainScreen;
    uic_Seconds = ui_Seconds;
    uic_amPmLabel = ui_amPmLabel;
    uic_mainSpinner = ui_mainSpinner;
    uic_tempArc = ui_tempArc;
    uic_tempLabel = ui_tempLabel;
    uic_WeatherContainer = ui_WeatherContainer;
    uic_Image2 = ui_Image2;
    uic_StatusContainer = ui_StatusContainer;
    uic_batteryContainer = ui_StatusContainer1;

}

void ui_mainScreen_screen_destroy(void)
{
    if(ui_mainScreen) lv_obj_del(ui_mainScreen);

    // NULL screen variables
    uic_mainScreen = NULL;
    ui_mainScreen = NULL;
    ui_Panel1 = NULL;
    ui_Hours = NULL;
    ui_colonone = NULL;
    ui_Minutes = NULL;
    ui_colonone2 = NULL;
    uic_Seconds = NULL;
    ui_Seconds = NULL;
    uic_amPmLabel = NULL;
    ui_amPmLabel = NULL;
    ui_Bar1 = NULL;
    ui_Container2 = NULL;
    ui_day = NULL;
    ui_monthDateYear = NULL;
    uic_mainSpinner = NULL;
    ui_mainSpinner = NULL;
    uic_tempArc = NULL;
    ui_tempArc = NULL;
    uic_tempLabel = NULL;
    ui_tempLabel = NULL;
    uic_WeatherContainer = NULL;
    ui_WeatherContainer = NULL;
    ui_monthDateYear1 = NULL;
    uic_Image2 = NULL;
    ui_Image2 = NULL;
    ui_Button1 = NULL;
    uic_StatusContainer = NULL;
    ui_StatusContainer = NULL;
    uic_batteryContainer = NULL;
    ui_StatusContainer1 = NULL;

}
