// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: RadioClock

#include "ui.h"

lv_obj_t * uic_backFromMusicToMenu;
lv_obj_t * uic_MusicScreen;
lv_obj_t * ui_MusicScreen = NULL;
lv_obj_t * ui_backFromMusicToMenu = NULL;
// event funtions
void ui_event_backFromMusicToMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 1500, 0, &ui_MenuScreen_screen_init);
    }
}

// build funtions

void ui_MusicScreen_screen_init(void)
{
    ui_MusicScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MusicScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MusicScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MusicScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MusicScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backFromMusicToMenu = lv_button_create(ui_MusicScreen);
    lv_obj_set_width(ui_backFromMusicToMenu, 81);
    lv_obj_set_height(ui_backFromMusicToMenu, 65);
    lv_obj_set_x(ui_backFromMusicToMenu, 115);
    lv_obj_set_y(ui_backFromMusicToMenu, 81);
    lv_obj_set_align(ui_backFromMusicToMenu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backFromMusicToMenu, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_backFromMusicToMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_backFromMusicToMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_backFromMusicToMenu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backFromMusicToMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_backFromMusicToMenu, &ui_img_angleleft_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_backFromMusicToMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_backFromMusicToMenu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_backFromMusicToMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_backFromMusicToMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_backFromMusicToMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_backFromMusicToMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_backFromMusicToMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_backFromMusicToMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_backFromMusicToMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_backFromMusicToMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_backFromMusicToMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_backFromMusicToMenu, &ui_img_angleleft_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_image_recolor(ui_backFromMusicToMenu, lv_color_hex(0xFFF400), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_image_recolor_opa(ui_backFromMusicToMenu, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_backFromMusicToMenu, ui_event_backFromMusicToMenu, LV_EVENT_ALL, NULL);
    uic_MusicScreen = ui_MusicScreen;
    uic_backFromMusicToMenu = ui_backFromMusicToMenu;

}

void ui_MusicScreen_screen_destroy(void)
{
    if(ui_MusicScreen) lv_obj_del(ui_MusicScreen);

    // NULL screen variables
    uic_MusicScreen = NULL;
    ui_MusicScreen = NULL;
    uic_backFromMusicToMenu = NULL;
    ui_backFromMusicToMenu = NULL;

}
