// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: RadioClock

#ifndef UI_RADIOSCREEN_H
#define UI_RADIOSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_RadioScreen
extern void ui_RadioScreen_screen_init(void);
extern void ui_RadioScreen_screen_destroy(void);
extern lv_obj_t * ui_RadioScreen;
extern lv_obj_t * ui_radioPageImg;
extern void ui_event_backFromMenuToMainScreen3(lv_event_t * e);
extern lv_obj_t * ui_backFromMenuToMainScreen3;
extern lv_obj_t * ui_Panel3;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_channel;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Panel4;
extern void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Image4;
// CUSTOM VARIABLES
extern lv_obj_t * uic_RadioScreen;
extern lv_obj_t * uic_radioPageImg;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

