// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: RadioClock

#include "ui.h"

lv_obj_t * uic_radioPageImg;
lv_obj_t * uic_RadioScreen;
lv_obj_t * ui_RadioScreen = NULL;
lv_obj_t * ui_radioPageImg = NULL;
lv_obj_t * ui_backFromMenuToMainScreen3 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_channel = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_Image4 = NULL;
// event funtions
void ui_event_backFromMenuToMainScreen3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 1500, 0, &ui_MenuScreen_screen_init);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_channel, 1);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_channel, -1);
    }
}

void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_image_set_property(ui_Image4, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_sound_png);
    }
}

// build funtions

void ui_RadioScreen_screen_init(void)
{
    ui_RadioScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_RadioScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RadioScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RadioScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RadioScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_radioPageImg = lv_image_create(ui_RadioScreen);
    lv_image_set_src(ui_radioPageImg, &ui_img_radio_png);
    lv_obj_set_width(ui_radioPageImg, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_radioPageImg, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_radioPageImg, 11);
    lv_obj_set_y(ui_radioPageImg, 4);
    lv_obj_add_flag(ui_radioPageImg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_radioPageImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_backFromMenuToMainScreen3 = lv_button_create(ui_RadioScreen);
    lv_obj_set_width(ui_backFromMenuToMainScreen3, 81);
    lv_obj_set_height(ui_backFromMenuToMainScreen3, 65);
    lv_obj_set_x(ui_backFromMenuToMainScreen3, 117);
    lv_obj_set_y(ui_backFromMenuToMainScreen3, 82);
    lv_obj_set_align(ui_backFromMenuToMainScreen3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backFromMenuToMainScreen3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_backFromMenuToMainScreen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_backFromMenuToMainScreen3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_backFromMenuToMainScreen3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backFromMenuToMainScreen3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_backFromMenuToMainScreen3, &ui_img_angleleft_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_backFromMenuToMainScreen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_backFromMenuToMainScreen3, lv_color_hex(0xFFFFFF),
                                      LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_backFromMenuToMainScreen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_backFromMenuToMainScreen3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_backFromMenuToMainScreen3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_backFromMenuToMainScreen3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_backFromMenuToMainScreen3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_backFromMenuToMainScreen3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_backFromMenuToMainScreen3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_backFromMenuToMainScreen3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_backFromMenuToMainScreen3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_backFromMenuToMainScreen3, &ui_img_angleleft_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_image_recolor(ui_backFromMenuToMainScreen3, lv_color_hex(0xFFF400),
                                      LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_image_recolor_opa(ui_backFromMenuToMainScreen3, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel3 = lv_obj_create(ui_RadioScreen);
    lv_obj_set_width(ui_Panel3, 205);
    lv_obj_set_height(ui_Panel3, 77);
    lv_obj_set_x(ui_Panel3, 105);
    lv_obj_set_y(ui_Panel3, 66);
    lv_obj_set_flex_flow(ui_Panel3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button2 = lv_button_create(ui_Panel3);
    lv_obj_set_width(ui_Button2, 40);
    lv_obj_set_height(ui_Button2, 40);
    lv_obj_set_x(ui_Button2, -57);
    lv_obj_set_y(ui_Button2, 0);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Button2, &ui_img_inc_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Button2, &ui_img_inc_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_image_recolor(ui_Button2, lv_color_hex(0x00E6FF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_image_recolor_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_channel = lv_spinbox_create(ui_Panel3);
    lv_obj_set_width(ui_channel, 77);
    lv_obj_set_height(ui_channel, 44);
    lv_obj_set_x(ui_channel, 127);
    lv_obj_set_y(ui_channel, 101);
    lv_spinbox_set_digit_format(ui_channel, 4, 3);
    lv_spinbox_set_range(ui_channel, 700, 1088);
    lv_spinbox_set_cursor_pos(ui_channel, 1 - 1);
    lv_obj_set_style_text_color(ui_channel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_channel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_channel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_button_create(ui_Panel3);
    lv_obj_set_width(ui_Button3, 40);
    lv_obj_set_height(ui_Button3, 40);
    lv_obj_set_x(ui_Button3, 62);
    lv_obj_set_y(ui_Button3, 0);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Button3, &ui_img_dec_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Button3, &ui_img_dec_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_image_recolor(ui_Button3, lv_color_hex(0x00E6FF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_image_recolor_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label8 = lv_label_create(ui_RadioScreen);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 42);
    lv_obj_set_y(ui_Label8, -85);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "SET CHANNEL");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_RadioScreen);
    lv_obj_set_width(ui_Panel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Panel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Panel4, 3);
    lv_obj_set_y(ui_Panel4, 70);
    lv_obj_set_flex_flow(ui_Panel4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_Panel4);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, -122);
    lv_obj_set_y(ui_Switch1, -23);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x00A0FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x8E00FF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Image4 = lv_image_create(ui_Panel4);
    lv_image_set_src(ui_Image4, &ui_img_mute_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image4, -120);
    lv_obj_set_y(ui_Image4, 40);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Image4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Image4, lv_color_hex(0x00D5FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Image4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Image4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Image4, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_backFromMenuToMainScreen3, ui_event_backFromMenuToMainScreen3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    uic_RadioScreen = ui_RadioScreen;
    uic_radioPageImg = ui_radioPageImg;

}

void ui_RadioScreen_screen_destroy(void)
{
    if(ui_RadioScreen) lv_obj_del(ui_RadioScreen);

    // NULL screen variables
    uic_RadioScreen = NULL;
    ui_RadioScreen = NULL;
    uic_radioPageImg = NULL;
    ui_radioPageImg = NULL;
    ui_backFromMenuToMainScreen3 = NULL;
    ui_Panel3 = NULL;
    ui_Button2 = NULL;
    ui_channel = NULL;
    ui_Button3 = NULL;
    ui_Label8 = NULL;
    ui_Panel4 = NULL;
    ui_Switch1 = NULL;
    ui_Image4 = NULL;

}
