// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: RadioClock

#include "ui.h"

lv_obj_t * uic_settingsScreen;
lv_obj_t * ui_settingsScreen = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_backFromMenuToMainScreen2 = NULL;
// event funtions
void ui_event_backFromMenuToMainScreen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 1500, 0, &ui_MenuScreen_screen_init);
    }
}

// build funtions

void ui_settingsScreen_screen_init(void)
{
    ui_settingsScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_settingsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settingsScreen, lv_color_hex(0x181829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingsScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_image_create(ui_settingsScreen);
    lv_image_set_src(ui_Image3, &ui_img_1725651404);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image3, -121);
    lv_obj_set_y(ui_Image3, -75);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_backFromMenuToMainScreen2 = lv_button_create(ui_settingsScreen);
    lv_obj_set_width(ui_backFromMenuToMainScreen2, 81);
    lv_obj_set_height(ui_backFromMenuToMainScreen2, 65);
    lv_obj_set_x(ui_backFromMenuToMainScreen2, 115);
    lv_obj_set_y(ui_backFromMenuToMainScreen2, 84);
    lv_obj_set_align(ui_backFromMenuToMainScreen2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backFromMenuToMainScreen2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_backFromMenuToMainScreen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_backFromMenuToMainScreen2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_backFromMenuToMainScreen2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backFromMenuToMainScreen2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_backFromMenuToMainScreen2, &ui_img_angleleft_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_backFromMenuToMainScreen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_backFromMenuToMainScreen2, lv_color_hex(0xFFFFFF),
                                      LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_backFromMenuToMainScreen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_backFromMenuToMainScreen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_backFromMenuToMainScreen2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_backFromMenuToMainScreen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_backFromMenuToMainScreen2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_backFromMenuToMainScreen2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_backFromMenuToMainScreen2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_backFromMenuToMainScreen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_backFromMenuToMainScreen2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_backFromMenuToMainScreen2, &ui_img_angleleft_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_image_recolor(ui_backFromMenuToMainScreen2, lv_color_hex(0xFFF400),
                                      LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_image_recolor_opa(ui_backFromMenuToMainScreen2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_backFromMenuToMainScreen2, ui_event_backFromMenuToMainScreen2, LV_EVENT_ALL, NULL);
    uic_settingsScreen = ui_settingsScreen;

}

void ui_settingsScreen_screen_destroy(void)
{
    if(ui_settingsScreen) lv_obj_del(ui_settingsScreen);

    // NULL screen variables
    uic_settingsScreen = NULL;
    ui_settingsScreen = NULL;
    ui_Image3 = NULL;
    ui_backFromMenuToMainScreen2 = NULL;

}
