// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: RadioClock

#ifndef UI_SETTINGSSCREEN_H
#define UI_SETTINGSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_settingsScreen
extern void ui_settingsScreen_screen_init(void);
extern void ui_settingsScreen_screen_destroy(void);
extern lv_obj_t * ui_settingsScreen;
extern lv_obj_t * ui_Image3;
extern void ui_event_backFromMenuToMainScreen2(lv_event_t * e);
extern lv_obj_t * ui_backFromMenuToMainScreen2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_settingsScreen;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

