// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: RadioClock

#ifndef UI_TIMESETTINGS_H
#define UI_TIMESETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_timeSettings
extern void ui_timeSettings_screen_init(void);
extern void ui_timeSettings_screen_destroy(void);
extern void ui_event_timeSettings(lv_event_t * e);
extern lv_obj_t * ui_timeSettings;
extern lv_obj_t * ui_TimeContainer;
extern lv_obj_t * ui_HourContainer;
extern lv_obj_t * ui_hourroller;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_MinuteContainer;
extern lv_obj_t * ui_minroller;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_SecondContainer;
extern lv_obj_t * ui_secroller;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_ampm;
extern lv_obj_t * ui_DDMMYYContainer;
extern lv_obj_t * ui_DateContainer;
extern lv_obj_t * ui_dateroller;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_MonthContainer;
extern lv_obj_t * ui_monroller;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_YearContainer;
extern lv_obj_t * ui_yearroller;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_DateTimeOkBtn;
extern void ui_event_backFromTimeSettingsToMainScreen(lv_event_t * e);
extern lv_obj_t * ui_backFromTimeSettingsToMainScreen;
// CUSTOM VARIABLES
extern lv_obj_t * uic_timeSettings;
extern lv_obj_t * uic_TimeContainer;
extern lv_obj_t * uic_HourContainer;
extern lv_obj_t * uic_hourroller;
extern lv_obj_t * uic_MinuteContainer;
extern lv_obj_t * uic_minroller;
extern lv_obj_t * uic_SecondContainer;
extern lv_obj_t * uic_secroller;
extern lv_obj_t * uic_ampm;
extern lv_obj_t * uic_DDMMYYContainer;
extern lv_obj_t * uic_DateContainer;
extern lv_obj_t * uic_dateroller;
extern lv_obj_t * uic_MonthContainer;
extern lv_obj_t * uic_monroller;
extern lv_obj_t * uic_YearContainer;
extern lv_obj_t * uic_yearroller;
extern lv_obj_t * uic_DateTimeOkBtn;
extern lv_obj_t * uic_backFromTimeSettingsToMainScreen;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

