// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: RadioClock

#include "ui.h"

lv_obj_t * uic_backFromTimeSettingsToMainScreen;
lv_obj_t * uic_DateTimeOkBtn;
lv_obj_t * uic_yearroller;
lv_obj_t * uic_YearContainer;
lv_obj_t * uic_monroller;
lv_obj_t * uic_MonthContainer;
lv_obj_t * uic_dateroller;
lv_obj_t * uic_DateContainer;
lv_obj_t * uic_DDMMYYContainer;
lv_obj_t * uic_ampm;
lv_obj_t * uic_secroller;
lv_obj_t * uic_SecondContainer;
lv_obj_t * uic_minroller;
lv_obj_t * uic_MinuteContainer;
lv_obj_t * uic_hourroller;
lv_obj_t * uic_HourContainer;
lv_obj_t * uic_TimeContainer;
lv_obj_t * uic_timeSettings;
lv_obj_t * ui_timeSettings = NULL;
lv_obj_t * ui_TimeContainer = NULL;
lv_obj_t * ui_HourContainer = NULL;
lv_obj_t * ui_hourroller = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_MinuteContainer = NULL;
lv_obj_t * ui_minroller = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_SecondContainer = NULL;
lv_obj_t * ui_secroller = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_ampm = NULL;
lv_obj_t * ui_DDMMYYContainer = NULL;
lv_obj_t * ui_DateContainer = NULL;
lv_obj_t * ui_dateroller = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_MonthContainer = NULL;
lv_obj_t * ui_monroller = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_YearContainer = NULL;
lv_obj_t * ui_yearroller = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_DateTimeOkBtn = NULL;
lv_obj_t * ui_backFromTimeSettingsToMainScreen = NULL;
// event funtions
void ui_event_timeSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_MenuScreen, LV_SCR_LOAD_ANIM_FADE_ON, 1500, 0, &ui_MenuScreen_screen_init);
    }
}

void ui_event_backFromTimeSettingsToMainScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 1500, 0, &ui_MenuScreen_screen_init);
    }
}

// build funtions

void ui_timeSettings_screen_init(void)
{
    ui_timeSettings = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_timeSettings, lv_color_hex(0x05070D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timeSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeContainer = lv_obj_create(ui_timeSettings);
    lv_obj_remove_style_all(ui_TimeContainer);
    lv_obj_set_width(ui_TimeContainer, 200);
    lv_obj_set_height(ui_TimeContainer, 119);
    lv_obj_set_x(ui_TimeContainer, 10);
    lv_obj_set_y(ui_TimeContainer, 7);
    lv_obj_set_flex_flow(ui_TimeContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TimeContainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TimeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TimeContainer, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TimeContainer, lv_color_hex(0x33FFF3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TimeContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TimeContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HourContainer = lv_obj_create(ui_TimeContainer);
    lv_obj_remove_style_all(ui_HourContainer);
    lv_obj_set_width(ui_HourContainer, 58);
    lv_obj_set_height(ui_HourContainer, 110);
    lv_obj_set_x(ui_HourContainer, -101);
    lv_obj_set_y(ui_HourContainer, -41);
    lv_obj_set_align(ui_HourContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_HourContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_HourContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_HourContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hourroller = lv_roller_create(ui_HourContainer);
    lv_roller_set_options(ui_hourroller, "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12", LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_hourroller, 5, LV_ANIM_OFF);
    lv_obj_set_width(ui_hourroller, 50);
    lv_obj_set_height(ui_hourroller, 90);
    lv_obj_set_x(ui_hourroller, 25);
    lv_obj_set_y(ui_hourroller, 86);
    lv_obj_set_style_shadow_color(ui_hourroller, lv_color_hex(0xD1D1D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_hourroller, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_hourroller, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_hourroller, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_hourroller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_hourroller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hourroller, &lv_font_montserrat_24, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_hourroller, lv_color_hex(0x5FBFF1), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hourroller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_hourroller, lv_color_hex(0x1635E3), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_hourroller, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_hourroller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_hourroller, LV_GRAD_DIR_HOR, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_HourContainer);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 42);
    lv_obj_set_y(ui_Label1, 123);
    lv_label_set_text(ui_Label1, "Hour");
    lv_obj_remove_flag(ui_Label1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MinuteContainer = lv_obj_create(ui_TimeContainer);
    lv_obj_remove_style_all(ui_MinuteContainer);
    lv_obj_set_width(ui_MinuteContainer, 59);
    lv_obj_set_height(ui_MinuteContainer, 120);
    lv_obj_set_x(ui_MinuteContainer, 102);
    lv_obj_set_y(ui_MinuteContainer, 18);
    lv_obj_set_flex_flow(ui_MinuteContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_MinuteContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MinuteContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_minroller = lv_roller_create(ui_MinuteContainer);
    lv_roller_set_options(ui_minroller,
                          "1\n2\n3\n4\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n",
                          LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_minroller, 10, LV_ANIM_OFF);
    lv_obj_set_width(ui_minroller, 50);
    lv_obj_set_height(ui_minroller, 90);
    lv_obj_set_x(ui_minroller, 201);
    lv_obj_set_y(ui_minroller, 20);
    lv_obj_set_style_shadow_color(ui_minroller, lv_color_hex(0xD1D1D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_minroller, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_minroller, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_minroller, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_minroller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_minroller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_minroller, &lv_font_montserrat_24, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_minroller, lv_color_hex(0x5FBFF1), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_minroller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_minroller, lv_color_hex(0x1635E3), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_minroller, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_minroller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_minroller, LV_GRAD_DIR_HOR, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_MinuteContainer);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 114);
    lv_obj_set_y(ui_Label2, 122);
    lv_label_set_text(ui_Label2, "Minute");
    lv_obj_remove_flag(ui_Label2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SecondContainer = lv_obj_create(ui_TimeContainer);
    lv_obj_remove_style_all(ui_SecondContainer);
    lv_obj_set_width(ui_SecondContainer, 63);
    lv_obj_set_height(ui_SecondContainer, 116);
    lv_obj_set_x(ui_SecondContainer, 171);
    lv_obj_set_y(ui_SecondContainer, 25);
    lv_obj_set_flex_flow(ui_SecondContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SecondContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SecondContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_secroller = lv_roller_create(ui_SecondContainer);
    lv_roller_set_options(ui_secroller,
                          "1\n2\n3\n4\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n",
                          LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_secroller, 35, LV_ANIM_OFF);
    lv_obj_set_width(ui_secroller, 50);
    lv_obj_set_height(ui_secroller, 90);
    lv_obj_set_x(ui_secroller, 200);
    lv_obj_set_y(ui_secroller, 24);
    lv_obj_set_style_shadow_color(ui_secroller, lv_color_hex(0xD1D1D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_secroller, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_secroller, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_secroller, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_secroller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_secroller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_secroller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_secroller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_secroller, &lv_font_montserrat_24, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_secroller, lv_color_hex(0x5FBFF1), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_secroller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_secroller, lv_color_hex(0x1635E3), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_secroller, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_secroller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_secroller, LV_GRAD_DIR_HOR, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_SecondContainer);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 181);
    lv_obj_set_y(ui_Label3, 122);
    lv_label_set_text(ui_Label3, "Seconds");
    lv_obj_remove_flag(ui_Label3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_timeSettings);
    lv_obj_set_width(ui_Panel2, 89);
    lv_obj_set_height(ui_Panel2, 67);
    lv_obj_set_x(ui_Panel2, 220);
    lv_obj_set_y(ui_Panel2, 8);
    lv_obj_set_flex_flow(ui_Panel2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x00EFFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ampm = lv_dropdown_create(ui_Panel2);
    lv_dropdown_set_options(ui_ampm, "AM\nPM");
    lv_obj_set_width(ui_ampm, 80);
    lv_obj_set_height(ui_ampm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ampm, -10);
    lv_obj_set_y(ui_ampm, -1);
    lv_obj_add_flag(ui_ampm, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_ampm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ampm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ampm, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ampm, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ampm, lv_color_hex(0x333131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ampm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ampm, lv_color_hex(0x6B6A6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ampm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ampm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ampm, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ampm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_ampm, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ampm, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_ampm), lv_color_hex(0xFFFFFF),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_ampm), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_ampm), lv_color_hex(0x626562),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_ampm), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(lv_dropdown_get_list(ui_ampm), lv_color_hex(0x393838),  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_ampm), lv_color_hex(0x0B7AFF),  LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_ampm), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(lv_dropdown_get_list(ui_ampm), lv_color_hex(0x000000),
                                  LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_dropdown_get_list(ui_ampm), 0,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_DDMMYYContainer = lv_obj_create(ui_timeSettings);
    lv_obj_remove_style_all(ui_DDMMYYContainer);
    lv_obj_set_width(ui_DDMMYYContainer, 200);
    lv_obj_set_height(ui_DDMMYYContainer, 110);
    lv_obj_set_x(ui_DDMMYYContainer, 11);
    lv_obj_set_y(ui_DDMMYYContainer, 130);
    lv_obj_set_flex_flow(ui_DDMMYYContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_DDMMYYContainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DDMMYYContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DDMMYYContainer, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DDMMYYContainer, lv_color_hex(0x33FFF3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DDMMYYContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DDMMYYContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateContainer = lv_obj_create(ui_DDMMYYContainer);
    lv_obj_remove_style_all(ui_DateContainer);
    lv_obj_set_width(ui_DateContainer, 58);
    lv_obj_set_height(ui_DateContainer, 110);
    lv_obj_set_x(ui_DateContainer, -101);
    lv_obj_set_y(ui_DateContainer, -41);
    lv_obj_set_align(ui_DateContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_DateContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_DateContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DateContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dateroller = lv_roller_create(ui_DateContainer);
    lv_roller_set_options(ui_dateroller,
                          "1\n2\n3\n4\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_dateroller, 50);
    lv_obj_set_height(ui_dateroller, 90);
    lv_obj_set_x(ui_dateroller, 25);
    lv_obj_set_y(ui_dateroller, 86);
    lv_obj_set_style_shadow_color(ui_dateroller, lv_color_hex(0xD1D1D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_dateroller, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_dateroller, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_dateroller, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_dateroller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dateroller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dateroller, &lv_font_montserrat_24, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dateroller, lv_color_hex(0x5FBFF1), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dateroller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_dateroller, lv_color_hex(0x1635E3), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_dateroller, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_dateroller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_dateroller, LV_GRAD_DIR_HOR, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_DateContainer);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 42);
    lv_obj_set_y(ui_Label5, 123);
    lv_label_set_text(ui_Label5, "Date");
    lv_obj_remove_flag(ui_Label5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MonthContainer = lv_obj_create(ui_DDMMYYContainer);
    lv_obj_remove_style_all(ui_MonthContainer);
    lv_obj_set_width(ui_MonthContainer, 59);
    lv_obj_set_height(ui_MonthContainer, 120);
    lv_obj_set_x(ui_MonthContainer, 102);
    lv_obj_set_y(ui_MonthContainer, 18);
    lv_obj_set_flex_flow(ui_MonthContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_MonthContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MonthContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_monroller = lv_roller_create(ui_MonthContainer);
    lv_roller_set_options(ui_monroller, "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_monroller, 50);
    lv_obj_set_height(ui_monroller, 90);
    lv_obj_set_x(ui_monroller, 201);
    lv_obj_set_y(ui_monroller, 20);
    lv_obj_set_style_shadow_color(ui_monroller, lv_color_hex(0xD1D1D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_monroller, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_monroller, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_monroller, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_monroller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_monroller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_monroller, &lv_font_montserrat_24, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_monroller, lv_color_hex(0x5FBFF1), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_monroller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_monroller, lv_color_hex(0x1635E3), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_monroller, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_monroller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_monroller, LV_GRAD_DIR_HOR, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_MonthContainer);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 114);
    lv_obj_set_y(ui_Label6, 122);
    lv_label_set_text(ui_Label6, "Month");
    lv_obj_remove_flag(ui_Label6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_YearContainer = lv_obj_create(ui_DDMMYYContainer);
    lv_obj_remove_style_all(ui_YearContainer);
    lv_obj_set_width(ui_YearContainer, 63);
    lv_obj_set_height(ui_YearContainer, 116);
    lv_obj_set_x(ui_YearContainer, 171);
    lv_obj_set_y(ui_YearContainer, 25);
    lv_obj_set_flex_flow(ui_YearContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_YearContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_YearContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_yearroller = lv_roller_create(ui_YearContainer);
    lv_roller_set_options(ui_yearroller,
                          "90\n91\n92\n93\n94\n95\n96\n97\n98\n99\n00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n60\n61\n62\n63\n64\n65\n66\n67\n68\n69\n70",
                          LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_yearroller, 36, LV_ANIM_OFF);
    lv_obj_set_width(ui_yearroller, 50);
    lv_obj_set_height(ui_yearroller, 90);
    lv_obj_set_x(ui_yearroller, 200);
    lv_obj_set_y(ui_yearroller, 24);
    lv_obj_set_style_shadow_color(ui_yearroller, lv_color_hex(0xD1D1D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_yearroller, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_yearroller, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_yearroller, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_yearroller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_yearroller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_yearroller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_yearroller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_yearroller, &lv_font_montserrat_24, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_yearroller, lv_color_hex(0x5FBFF1), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_yearroller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_yearroller, lv_color_hex(0x1635E3), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_yearroller, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_yearroller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_yearroller, LV_GRAD_DIR_HOR, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_YearContainer);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 181);
    lv_obj_set_y(ui_Label7, 122);
    lv_label_set_text(ui_Label7, "Year");
    lv_obj_add_flag(ui_Label7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Label7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateTimeOkBtn = lv_button_create(ui_timeSettings);
    lv_obj_set_width(ui_DateTimeOkBtn, 93);
    lv_obj_set_height(ui_DateTimeOkBtn, 80);
    lv_obj_set_x(ui_DateTimeOkBtn, 219);
    lv_obj_set_y(ui_DateTimeOkBtn, 80);
    lv_obj_add_flag(ui_DateTimeOkBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_DateTimeOkBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DateTimeOkBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DateTimeOkBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_DateTimeOkBtn, &ui_img_set_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DateTimeOkBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DateTimeOkBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DateTimeOkBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_DateTimeOkBtn, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_DateTimeOkBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_DateTimeOkBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DateTimeOkBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DateTimeOkBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DateTimeOkBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DateTimeOkBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_DateTimeOkBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_DateTimeOkBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DateTimeOkBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_DateTimeOkBtn, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_image_src(ui_DateTimeOkBtn, &ui_img_ok_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_DateTimeOkBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_DateTimeOkBtn, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_DateTimeOkBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_DateTimeOkBtn, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_backFromTimeSettingsToMainScreen = lv_button_create(ui_timeSettings);
    lv_obj_set_width(ui_backFromTimeSettingsToMainScreen, 81);
    lv_obj_set_height(ui_backFromTimeSettingsToMainScreen, 65);
    lv_obj_set_x(ui_backFromTimeSettingsToMainScreen, 105);
    lv_obj_set_y(ui_backFromTimeSettingsToMainScreen, 76);
    lv_obj_set_align(ui_backFromTimeSettingsToMainScreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backFromTimeSettingsToMainScreen, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_backFromTimeSettingsToMainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_backFromTimeSettingsToMainScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_backFromTimeSettingsToMainScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backFromTimeSettingsToMainScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_backFromTimeSettingsToMainScreen, &ui_img_angleleft_png,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_backFromTimeSettingsToMainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_backFromTimeSettingsToMainScreen, lv_color_hex(0xFFFFFF),
                                      LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_backFromTimeSettingsToMainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_backFromTimeSettingsToMainScreen, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_backFromTimeSettingsToMainScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_backFromTimeSettingsToMainScreen, lv_color_hex(0x000000),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_backFromTimeSettingsToMainScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_backFromTimeSettingsToMainScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_backFromTimeSettingsToMainScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_backFromTimeSettingsToMainScreen, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_backFromTimeSettingsToMainScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_backFromTimeSettingsToMainScreen, &ui_img_angleleft_png,
                                  LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_image_recolor(ui_backFromTimeSettingsToMainScreen, lv_color_hex(0xFFF400),
                                      LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_image_recolor_opa(ui_backFromTimeSettingsToMainScreen, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_backFromTimeSettingsToMainScreen, ui_event_backFromTimeSettingsToMainScreen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_timeSettings, ui_event_timeSettings, LV_EVENT_ALL, NULL);
    uic_timeSettings = ui_timeSettings;
    uic_TimeContainer = ui_TimeContainer;
    uic_HourContainer = ui_HourContainer;
    uic_hourroller = ui_hourroller;
    uic_MinuteContainer = ui_MinuteContainer;
    uic_minroller = ui_minroller;
    uic_SecondContainer = ui_SecondContainer;
    uic_secroller = ui_secroller;
    uic_ampm = ui_ampm;
    uic_DDMMYYContainer = ui_DDMMYYContainer;
    uic_DateContainer = ui_DateContainer;
    uic_dateroller = ui_dateroller;
    uic_MonthContainer = ui_MonthContainer;
    uic_monroller = ui_monroller;
    uic_YearContainer = ui_YearContainer;
    uic_yearroller = ui_yearroller;
    uic_DateTimeOkBtn = ui_DateTimeOkBtn;
    uic_backFromTimeSettingsToMainScreen = ui_backFromTimeSettingsToMainScreen;

}

void ui_timeSettings_screen_destroy(void)
{
    if(ui_timeSettings) lv_obj_del(ui_timeSettings);

    // NULL screen variables
    uic_timeSettings = NULL;
    ui_timeSettings = NULL;
    uic_TimeContainer = NULL;
    ui_TimeContainer = NULL;
    uic_HourContainer = NULL;
    ui_HourContainer = NULL;
    uic_hourroller = NULL;
    ui_hourroller = NULL;
    ui_Label1 = NULL;
    uic_MinuteContainer = NULL;
    ui_MinuteContainer = NULL;
    uic_minroller = NULL;
    ui_minroller = NULL;
    ui_Label2 = NULL;
    uic_SecondContainer = NULL;
    ui_SecondContainer = NULL;
    uic_secroller = NULL;
    ui_secroller = NULL;
    ui_Label3 = NULL;
    ui_Panel2 = NULL;
    uic_ampm = NULL;
    ui_ampm = NULL;
    uic_DDMMYYContainer = NULL;
    ui_DDMMYYContainer = NULL;
    uic_DateContainer = NULL;
    ui_DateContainer = NULL;
    uic_dateroller = NULL;
    ui_dateroller = NULL;
    ui_Label5 = NULL;
    uic_MonthContainer = NULL;
    ui_MonthContainer = NULL;
    uic_monroller = NULL;
    ui_monroller = NULL;
    ui_Label6 = NULL;
    uic_YearContainer = NULL;
    ui_YearContainer = NULL;
    uic_yearroller = NULL;
    ui_yearroller = NULL;
    ui_Label7 = NULL;
    uic_DateTimeOkBtn = NULL;
    ui_DateTimeOkBtn = NULL;
    uic_backFromTimeSettingsToMainScreen = NULL;
    ui_backFromTimeSettingsToMainScreen = NULL;

}
