// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: RadioClock

#ifndef UI_WIFISCREEN_H
#define UI_WIFISCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WifiScreen
extern void ui_WifiScreen_screen_init(void);
extern void ui_WifiScreen_screen_destroy(void);
extern lv_obj_t * ui_WifiScreen;
extern void ui_event_backFromWifiToMenu(lv_event_t * e);
extern lv_obj_t * ui_backFromWifiToMenu;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_WifiDropDown;
extern lv_obj_t * ui_ScanWifi;
extern lv_obj_t * ui_wifiButtonLabel;
extern lv_obj_t * ui_InputContainer;
extern lv_obj_t * ui_passwordTextArea;
extern lv_obj_t * ui_passwordContainer;
extern lv_obj_t * ui_CancelWifiBtn;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_OKWifiBtn;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_passwordKeyboard;
// CUSTOM VARIABLES
extern lv_obj_t * uic_WifiScreen;
extern lv_obj_t * uic_backFromWifiToMenu;
extern lv_obj_t * uic_WifiDropDown;
extern lv_obj_t * uic_wifiButtonLabel;
extern lv_obj_t * uic_InputContainer;
extern lv_obj_t * uic_passwordTextArea;
extern lv_obj_t * uic_passwordContainer;
extern lv_obj_t * uic_CancelWifiBtn;
extern lv_obj_t * uic_OKWifiBtn;
extern lv_obj_t * uic_passwordKeyboard;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

