// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: RadioClock

#include "ui.h"

lv_obj_t * uic_WifiDropDown;
lv_obj_t * uic_backFromWifiToMenu;
lv_obj_t * uic_WifiScreen;
lv_obj_t * ui_WifiScreen = NULL;
lv_obj_t * ui_backFromWifiToMenu = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_WifiDropDown = NULL;
lv_obj_t * ui_ScanWifi = NULL;
lv_obj_t * ui_Label13 = NULL;
// event funtions
void ui_event_backFromWifiToMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 1500, 0, &ui_MenuScreen_screen_init);
    }
}

// build funtions

void ui_WifiScreen_screen_init(void)
{
    ui_WifiScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_WifiScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backFromWifiToMenu = lv_button_create(ui_WifiScreen);
    lv_obj_set_width(ui_backFromWifiToMenu, 81);
    lv_obj_set_height(ui_backFromWifiToMenu, 65);
    lv_obj_set_x(ui_backFromWifiToMenu, 115);
    lv_obj_set_y(ui_backFromWifiToMenu, 81);
    lv_obj_set_align(ui_backFromWifiToMenu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backFromWifiToMenu, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_backFromWifiToMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_backFromWifiToMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_backFromWifiToMenu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backFromWifiToMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_backFromWifiToMenu, &ui_img_angleleft_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_backFromWifiToMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_backFromWifiToMenu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_backFromWifiToMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_backFromWifiToMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_backFromWifiToMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_backFromWifiToMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_backFromWifiToMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_backFromWifiToMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_backFromWifiToMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_backFromWifiToMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_backFromWifiToMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_backFromWifiToMenu, &ui_img_angleleft_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_image_recolor(ui_backFromWifiToMenu, lv_color_hex(0xFFF400), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_image_recolor_opa(ui_backFromWifiToMenu, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Container3 = lv_obj_create(ui_WifiScreen);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 285);
    lv_obj_set_height(ui_Container3, 41);
    lv_obj_set_x(ui_Container3, -3);
    lv_obj_set_y(ui_Container3, -82);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_remove_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiDropDown = lv_dropdown_create(ui_Container3);
    lv_dropdown_set_options(ui_WifiDropDown, "Option 1\nOption 2\nOption 3");
    lv_obj_set_width(ui_WifiDropDown, 205);
    lv_obj_set_height(ui_WifiDropDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiDropDown, -33);
    lv_obj_set_y(ui_WifiDropDown, 2);
    lv_obj_set_align(ui_WifiDropDown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiDropDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_ScanWifi = lv_button_create(ui_Container3);
    lv_obj_set_width(ui_ScanWifi, 67);
    lv_obj_set_height(ui_ScanWifi, 35);
    lv_obj_set_x(ui_ScanWifi, 83);
    lv_obj_set_y(ui_ScanWifi, 14);
    lv_obj_add_flag(ui_ScanWifi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ScanWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScanWifi, lv_color_hex(0xA2D91A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScanWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ScanWifi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScanWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_ScanWifi);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Scan");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_backFromWifiToMenu, ui_event_backFromWifiToMenu, LV_EVENT_ALL, NULL);
    uic_WifiScreen = ui_WifiScreen;
    uic_backFromWifiToMenu = ui_backFromWifiToMenu;
    uic_WifiDropDown = ui_WifiDropDown;

}

void ui_WifiScreen_screen_destroy(void)
{
    if(ui_WifiScreen) lv_obj_del(ui_WifiScreen);

    // NULL screen variables
    uic_WifiScreen = NULL;
    ui_WifiScreen = NULL;
    uic_backFromWifiToMenu = NULL;
    ui_backFromWifiToMenu = NULL;
    ui_Container3 = NULL;
    uic_WifiDropDown = NULL;
    ui_WifiDropDown = NULL;
    ui_ScanWifi = NULL;
    ui_Label13 = NULL;

}
